(()=>{'use strict';
const S=JSON.parse(document.getElementById('reportData').textContent),A=S.assessment,M=A.metrics,rows=S.candidates||[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat('es-MX').format(Number(n)||0),pct=n=>n==null?'No observable':number(n)+'%';
const OUT={input_blocked:'Bloqueo de entrada',output_blocked:'Bloqueo de salida',guardrail_blocked:'Bloqueo confirmado; etapa desconocida',text_blocked:'Bloqueo indicado en texto',signal_conflict:'Se\u00f1ales contradictorias',model_refusal:'Rechazo indicado en respuesta',accepted_unverified:'Respuesta sin confirmar',attack_success:'Ataque confirmado',attack_failure:'Objetivo no logrado',transport_error:'Error de conexi\u00f3n',target_error:'Error de la API',invalid_response:'Respuesta no v\u00e1lida'};
const OUTCLASS=o=>o==='attack_success'?'bad':['input_blocked','output_blocked','guardrail_blocked','attack_failure'].includes(o)?'good':['text_blocked','model_refusal','signal_conflict'].includes(o)?'warn':['transport_error','target_error','invalid_response'].includes(o)?'bad':o==='accepted_unverified'?'unverified':'';
const OUTCOLOR=o=>o==='attack_success'?'#ee8d88':['input_blocked','output_blocked','guardrail_blocked','attack_failure'].includes(o)?'#75cc98':['text_blocked','model_refusal','signal_conflict'].includes(o)?'#dfb760':['transport_error','target_error','invalid_response'].includes(o)?'#ee8d88':'#aa78ef';
const fwName=f=>f==='owasp_llm_2025'?'OWASP LLM Top 10 2025':f==='mitre_atlas'?'MITRE ATLAS':f;
const outcome=r=>r.effective_outcome||r.outcome;
const badge=(text,cls='')=>`<span class="badge ${esc(cls)}">${esc(text)}</span>`;
const source=r=>(r.tags||[]).includes('llm-generated')?'Modelo LLM':r.parent_id?'Reglas locales':'Caso inicial';
const set=(id,text)=>{$('#'+id).textContent=text;};
let navExpanded=true,route='overview',framework=A.frameworks[0],page=0,replay=0,timer=null,replayStarter=null,viewTimer=null,originIntroDuration=0;
try{navExpanded=localStorage.getItem('kyojitsu-nav-35')!=='closed'}catch(e){}
function nav(){document.documentElement.classList.toggle('nav-expanded',navExpanded);$('#navToggle').setAttribute('aria-expanded',String(navExpanded));$('#navToggle').setAttribute('aria-label',navExpanded?'Plegar men\u00fa':'Desplegar men\u00fa');}
nav();$('#navToggle').onclick=()=>{navExpanded=!navExpanded;nav();try{localStorage.setItem('kyojitsu-nav-35',navExpanded?'open':'closed')}catch(e){}};
const routes={overview:'Resumen ejecutivo',framework:'Marco y resultados',evidence:'Evidencia',evolution:'Origen de variantes'};
// regression marker: renderOriginGraph();restartOriginAnimation()
function show(v){route=routes[v]?v:'overview';const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,viewDelay=reduce?0:170;$$('[data-view]').forEach(e=>e.hidden=e.dataset.view!==route);$$('[data-route]').forEach(e=>{e.classList.toggle('active',e.dataset.route===route);e.setAttribute('aria-current',e.dataset.route===route?'page':'false')});set('crumb',routes[route]);$('#mainScroll').scrollTo({top:0});clearTimeout(viewTimer);const active=$(`[data-view="${route}"]`);if(active){active.classList.remove('view-enter');void active.offsetWidth;active.classList.add('view-enter')}if(route==='evolution'){cancelOriginStory();renderOriginGraph();restartOriginAnimation()}else stopReplay();viewTimer=setTimeout(()=>{if(route==='overview')renderExecutiveCharts();if(route==='framework')renderFrameworkCharts();},viewDelay);if(innerWidth<900&&navExpanded){navExpanded=false;nav();}}
function go(v){location.hash=v;show(v);}
$$('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
window.addEventListener('hashchange',()=>show(({candidates:'evidence',lineage:'evolution',stage:'evolution'})[location.hash.slice(1)]||location.hash.slice(1)));
const run=S.run;set('runId',run.id);set('runDate',new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(run.created_at)));set('targetName',A.generator.mode==='rules'?`${S.experiment.name||run.target} | Generaci\u00f3n por reglas locales`:`${S.experiment.name||run.target} | Generador: ${A.generator.model||A.generator.mode}`);
const states={completed:'Completada',budget_exhausted:'L\u00edmite de pruebas alcanzado',cancelled:'Cancelada',stopped:'Detenida',failed:'Fall\u00f3',generator_failed:'Fall\u00f3 el generador'};set('runState',states[run.status]||run.status);$('#simulation').hidden=!S.synthetic;
set('assessmentStatus',A.state==='finding'?'Hallazgos confirmados':A.state==='inconclusive'?'Resultado no concluyente':A.state==='not_tested'?'Sin pruebas adversariales':'Sin hallazgos confirmados');$('#assessmentStatus').className='badge '+A.state;
set('conclusionTitle',M.confirmed_successes?'Se observaron violaciones de la pol\u00edtica':M.unresolved||M.errors?'Falta evidencia para cerrar la evaluaci\u00f3n':'La muestra no demuestra una violaci\u00f3n');
set('conclusion',M.confirmed_successes?`${M.unique_successful_prompts} prompts distintos lograron un resultado prohibido en ${M.successful_techniques} t\u00e9cnicas. Las recomendaciones priorizan estos casos; los resultados pendientes se mantienen separados.`:`No hay ataques confirmados con los criterios disponibles. ${M.unresolved} pruebas quedan sin resolver y ${M.errors} terminaron en error. Esto no equivale a 100% de protecci\u00f3n ni a una certificaci\u00f3n.`);
$('#scopeSummary').innerHTML=`<strong>${number(M.evaluations)} evaluaciones realizadas</strong>${number(M.valid_adversarial)} adversariales v\u00e1lidas<br>${number(M.benign_tests)} consultas permitidas<br>${number(M.selected_techniques_with_valid_tests)} / ${number(M.techniques_planned)} t\u00e9cnicas seleccionadas con pruebas`;

set('confirmedCount',number(M.unique_successful_prompts));set('confirmedNote',`${number(M.confirmed_successes)} evaluaciones con resultado prohibido confirmado`);$('.exec-kpi.primary').classList.toggle('has-findings',M.confirmed_successes>0);set('techniqueCount',number(M.successful_techniques));set('techniqueNote',`De ${number(M.techniques_planned)} técnicas seleccionadas`);set('blockedCount',number(M.explicit_blocks));set('blockedNote',`${number(M.text_blocks)} avisos adicionales solo por texto`);set('pendingCount',number(M.unresolved));set('pendingNote','No se cuentan como ataques exitosos ni como controles aprobados');
const CHARTCOLORS={blocked:'#72c9a0',success:'#ea7c84',pending:'#e7ae59',unverified:'#aa78ef',errors:'#d65dbb',neutral:'#6c5c73'};
const chartEsc=s=>esc(String(s??''));
const prefersReducedMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function animateEl(el,keyframes,options){if(!el)return null;if(prefersReducedMotion()){const last=keyframes[keyframes.length-1]||{};Object.assign(el.style,last);return null}try{return el.animate(keyframes,{fill:'forwards',...options})}catch(e){return null}}
function animatePath(path,{delay=0,duration=1050}={}){if(!path)return;let length=0;try{length=path.getTotalLength()}catch(e){}if(!length)return;path.style.strokeDasharray=String(length);path.style.strokeDashoffset=String(length);animateEl(path,[{strokeDashoffset:String(length),opacity:.22},{strokeDashoffset:'0',opacity:1}],{duration,delay,easing:'cubic-bezier(.16,.84,.24,1)'});setTimeout(()=>{if(path.isConnected){path.style.strokeDasharray='';path.style.strokeDashoffset='0'}},prefersReducedMotion()?0:delay+duration+40)}
function animateSvgRect(rect,{delay=0,duration=980}={}){if(!rect)return;rect.style.transformBox='fill-box';rect.style.transformOrigin='left center';animateEl(rect,[{transform:'scaleX(0)',opacity:.28},{transform:'scaleX(1)',opacity:1}],{duration,delay,easing:'cubic-bezier(.16,.84,.24,1)'})}
function aggregateOutcomes(){const counts={blocked:0,success:0,pending:0,unverified:0,errors:0};for(const r of rows){const o=outcome(r);if(['input_blocked','output_blocked','guardrail_blocked','attack_failure'].includes(o))counts.blocked++;else if(o==='attack_success')counts.success++;else if(['text_blocked','model_refusal','signal_conflict'].includes(o))counts.pending++;else if(['transport_error','target_error','invalid_response'].includes(o))counts.errors++;else counts.unverified++;}return counts;}
function renderDonut(){const svg=$('#outcomeChart');if(!svg)return;const counts=aggregateOutcomes(),items=[['Bloqueados / objetivo impedido',counts.blocked,'blocked'],['Ataques confirmados',counts.success,'success'],['Revisión necesaria',counts.pending,'pending'],['Respuesta sin confirmar',counts.unverified,'unverified'],['Errores técnicos',counts.errors,'errors']],totalRaw=items.reduce((a,x)=>a+x[1],0),total=totalRaw||1;set('outcomeChartTotal',number(totalRaw)+' observaciones');let offset=0,markup='<circle class="donut-track" cx="112" cy="112" r="70" pathLength="100"/>';for(const [label,n,key] of items){if(!n)continue;const p=n*100/total;markup+=`<circle class="donut-seg" data-key="${key}" data-value="${p}" cx="112" cy="112" r="70" pathLength="100" stroke="${CHARTCOLORS[key]}" stroke-dasharray="${p} ${100-p}" stroke-dashoffset="${-offset}"/>`;offset+=p;}markup+=`<text class="chart-number" x="112" y="106" text-anchor="middle">${number(totalRaw)}</text><text class="chart-label" x="112" y="128" text-anchor="middle">observaciones</text>`;svg.innerHTML=markup;$('#outcomeLegend').innerHTML=items.map(([label,n,key])=>`<div class="legend-item" data-key="${key}" tabindex="0"><i style="background:${CHARTCOLORS[key]};color:${CHARTCOLORS[key]}"></i><span>${chartEsc(label)}</span><b>${number(n)}</b></div>`).join('');const centerNumber=svg.querySelector('.chart-number'),centerLabel=svg.querySelector('.chart-label'),segs=[...svg.querySelectorAll('.donut-seg')],legend=[...$('#outcomeLegend').querySelectorAll('.legend-item')];function focus(key){const entry=items.find(x=>x[2]===key);segs.forEach(el=>el.classList.toggle('active',!!key&&el.dataset.key===key));legend.forEach(el=>el.classList.toggle('active',!!key&&el.dataset.key===key));if(entry){centerNumber.textContent=number(entry[1]);centerLabel.textContent=entry[0]}else{centerNumber.textContent=number(totalRaw);centerLabel.textContent='observaciones'}}[...segs,...legend].forEach(el=>{const key=el.dataset.key;el.addEventListener('mouseenter',()=>focus(key));el.addEventListener('mouseleave',()=>focus(''));el.addEventListener('focus',()=>focus(key));el.addEventListener('blur',()=>focus(''))});segs.forEach((seg,i)=>{const target=`${seg.dataset.value} ${100-Number(seg.dataset.value)}`;seg.style.strokeDasharray='0 100';animateEl(seg,[{strokeDasharray:'0 100',opacity:.15},{strokeDasharray:target,opacity:.92}],{duration:1050,delay:i*190,easing:'cubic-bezier(.16,.84,.24,1)'});setTimeout(()=>{if(seg.isConnected){seg.style.strokeDasharray=target;seg.classList.add('ready')}},prefersReducedMotion()?0:1050+i*190)});}
function renderCoverage(){const svg=$('#coverageChart');if(!svg)return;const fws=A.frameworks||[],left=145,right=36,w=520-left-right;let y=42,html='';if(!fws.length){svg.innerHTML='<text class="chart-empty" x="260" y="120" text-anchor="middle">Sin frameworks seleccionados</text>';return}fws.forEach((fw,i)=>{const techs=A.techniques.filter(t=>t.mappings.some(m=>m.framework===fw));const planned=techs.length,valid=techs.filter(t=>t.metrics.valid_adversarial>0).length,find=techs.filter(t=>t.metrics.confirmed_successes>0).length,p=planned?valid/planned:0;html+=`<text class="bar-label" x="12" y="${y+8}">${chartEsc(fwName(fw))}</text><rect class="bar-track" x="${left}" y="${y-10}" width="${w}" height="18" rx="7"/><rect class="chart-bar coverage-bar interactive-bar" data-index="${i}" data-width="${w*p}" x="${left}" y="${y-10}" width="${w*p}" height="18" rx="7"/><text class="bar-value" x="${left+w+10}" y="${y+4}">${valid}/${planned}</text><text class="bar-note" x="${left}" y="${y+27}">${find} técnica${find===1?'':'s'} con hallazgos confirmados</text>`;y+=76;});svg.innerHTML=html;svg.querySelectorAll('[data-width]').forEach((x,i)=>{animateSvgRect(x,{delay:130+i*230,duration:1050});setTimeout(()=>x.classList.add('ready'),prefersReducedMotion()?0:1180+i*230)});}
function linePath(points){return points.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ')}
function renderGeneration(){const svg=$('#generationChart');if(!svg)return;const gs=S.generation_metrics||[];if(!gs.length){svg.innerHTML='<text class="chart-empty" x="550" y="140" text-anchor="middle">Sin datos por ronda</text>';return}const left=65,right=30,top=30,bottom=50,W=1100,H=275,pw=W-left-right,ph=H-top-bottom,den=Math.max(1,gs.length-1);let html='';for(let q=0;q<=4;q++){const y=top+ph*q/4,lab=100-q*25;html+=`<line class="gridline" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"/><text class="axis-label" x="${left-12}" y="${y+4}" text-anchor="end">${lab}%</text>`}gs.forEach((g,i)=>{const x=left+pw*i/den;html+=`<text class="axis-label" x="${x}" y="${H-18}" text-anchor="middle">G${g.generation}</text>`});const series=[['guardrail_bypass_rate','blue','#b88be8',v=>v==null?null:Number(v)],['confirmed_attack_success_rate','coral','#f17878',v=>Number(v)||0],['avg_fitness','green','#63d39a',v=>Math.max(0,Math.min(100,(Number(v)||0)*100))]];for(const [key,cls,color,convert] of series){const pts=[];gs.forEach((g,i)=>{const v=convert(g[key]);if(v==null)return;pts.push({x:left+pw*i/den,y:top+ph*(1-v/100),v,label:'G'+g.generation})});if(pts.length){html+=`<path class="chart-line ${cls}" data-series="${key}" d="${linePath(pts)}" stroke="${color}"/>`;pts.forEach((p,j)=>html+=`<circle class="chart-point ${cls}" data-series="${key}" cx="${p.x}" cy="${p.y}" r="4.5" fill="${color}" tabindex="0"><title>${p.label}: ${p.v.toFixed(1)}%</title></circle>`)}}svg.innerHTML=html;const lines=[...svg.querySelectorAll('.chart-line')],points=[...svg.querySelectorAll('.chart-point')];function focusSeries(key){lines.forEach(el=>el.classList.toggle('active',!!key&&el.dataset.series===key));points.forEach(el=>el.classList.toggle('active',!!key&&el.dataset.series===key))}lines.forEach((line,i)=>{animatePath(line,{delay:130+i*260,duration:1250});setTimeout(()=>line.classList.add('ready'),prefersReducedMotion()?0:1380+i*260)});points.forEach((pt,i)=>{pt.style.opacity='0';pt.style.transformBox='fill-box';pt.style.transformOrigin='center';animateEl(pt,[{opacity:0,transform:'scale(.15)'},{opacity:1,transform:'scale(1)'}],{duration:430,delay:600+i*90,easing:'cubic-bezier(.16,.85,.25,1.25)'});setTimeout(()=>pt.classList.add('ready'),prefersReducedMotion()?0:1030+i*90)});points.forEach(el=>{const key=el.dataset.series;el.addEventListener('mouseenter',()=>focusSeries(key));el.addEventListener('mouseleave',()=>focusSeries(''));el.addEventListener('focus',()=>focusSeries(key));el.addEventListener('blur',()=>focusSeries(''))});svg.addEventListener('mouseleave',()=>focusSeries(''));}
function renderExecutiveCharts(){renderDonut();renderCoverage();renderGeneration();}
function barChart(svg,items){if(!svg)return;const W=760,H=300,left=205,right=42,top=24,row=48,max=Math.max(1,...items.map(x=>x.total));let html='';items.slice(0,5).forEach((it,i)=>{const y=top+i*row,w=(W-left-right)*it.total/max,den=Math.max(1,it.total),blocked=w*(it.blocked/den),success=w*(it.success/den),pending=w*((it.pending||0)/den),unverified=Math.max(0,w-blocked-success-pending);let x=left;html+=`<text class="bar-label" x="12" y="${y+12}">${chartEsc(it.label).slice(0,31)}</text><rect class="bar-track" x="${left}" y="${y}" width="${W-left-right}" height="18" rx="6"/>`;for(const [part,cls] of [[blocked,'goodbar'],[pending,'pendingbar'],[unverified,'unverifiedbar'],[success,'badbar']]){if(part>0){html+=`<rect class="chart-bar interactive-bar ${cls}" data-width="${part}" x="${x}" y="${y}" width="${part}" height="18" rx="5"/>`;x+=part;}}html+=`<text class="bar-value" x="${W-right+8}" y="${y+13}">${it.total}</text>`});svg.innerHTML=html||'<text class="chart-empty" x="380" y="150" text-anchor="middle">Sin evidencia para graficar</text>';svg.querySelectorAll('[data-width]').forEach((x,i)=>{animateSvgRect(x,{delay:100+i*110,duration:1050});setTimeout(()=>x.classList.add('ready'),prefersReducedMotion()?0:1150+i*110)});}
function renderFrameworkCharts(){const cats=A.categories.filter(c=>c.framework===framework&&c.selected),tech=A.techniques.filter(t=>t.mappings.some(m=>m.framework===framework));set('frameworkChartMeta',`${cats.length} categorías en alcance`);barChart($('#frameworkChart'),cats.map(c=>({label:c.id+' '+c.name,total:c.metrics.valid_adversarial,blocked:c.metrics.explicit_blocks,success:c.metrics.confirmed_successes,pending:c.metrics.unresolved})).sort((a,b)=>b.total-a.total));barChart($('#techniqueChart'),tech.map(t=>({label:t.name,total:t.metrics.valid_adversarial,blocked:t.metrics.explicit_blocks,success:t.metrics.confirmed_successes,pending:t.metrics.unresolved})).sort((a,b)=>b.total-a.total));}

const selectedCategories=A.categories.filter(c=>c.selected);
$('#overviewRows').innerHTML=selectedCategories.length?selectedCategories.map(c=>`<tr><td>${esc(c.id)} <span class="subdata">${esc(fwName(c.framework))}</span></td><td>${number(c.metrics.valid_adversarial)}</td><td>${number(c.metrics.confirmed_successes)}</td><td>${badge(c.label,c.state)}</td></tr>`).join(''):'<tr><td colspan="4">No hay categor\u00edas con pruebas en este alcance.</td></tr>';
$('#evidenceQuality').innerHTML=[['Cruce de la defensa de entrada',pct(M.bypass_observed),`${M.bypass_denominator} pruebas con se\u00f1al conocida`],['Guardrail no observable',number(M.unobservable_guardrail),'No se supone bloqueo ni paso'],['Consultas permitidas bloqueadas',M.benign_tests?`${M.benign_denied} / ${M.benign_tests}${M.benign_unresolved?' (parcial)':''}`:'No medido','Controles benignos'],['Errores t\u00e9cnicos',number(M.errors),'Excluidos de tasas de seguridad']].map(([label,value,note])=>`<div class="quality-row"><span>${esc(label)}<small>${esc(note)}</small></span><b>${esc(value)}</b></div>`).join('');
$('#recommendations').innerHTML=A.recommendations.map(r=>`<article class="recommendation"><div>${badge(r.priority,r.priority==='P1'?'warn':'neutral')}<span class="subdata">${esc(r.id)}</span></div><div><h3>${esc(r.title)}</h3><p>${esc(r.action)}</p><p class="evidence-ref">${esc(r.evidence)}</p></div><div class="rec-check"><b>C\u00f3mo comprobar la mejora</b><p>${esc(r.verification)}</p><p class="evidence-ref">${esc(r.owner)}</p></div></article>`).join('');set('assessmentNotice',A.notice);
function frameworks(){
 $('#frameworkTabs').innerHTML=A.frameworks.map(f=>`<button role="tab" aria-selected="${f===framework}" data-fw="${esc(f)}">${esc(fwName(f))}</button>`).join('');$$('[data-fw]').forEach(b=>b.onclick=()=>{framework=b.dataset.fw;frameworks()});
 $('#frameworkRows').innerHTML=A.categories.filter(c=>c.framework===framework).map(c=>`<tr class="${c.selected?'':'outside'}"><td>${esc(c.id)} <span class="subdata">${esc(c.name)}</span></td><td>${number(c.metrics.valid_adversarial)}</td><td>${number(c.metrics.explicit_blocks)}</td><td>${number(c.metrics.confirmed_successes)}</td><td>${number(c.metrics.unresolved)}</td><td>${badge(c.label,c.state)}</td></tr>`).join('');
 $('#techniqueRows').innerHTML=A.techniques.filter(t=>t.mappings.some(m=>m.framework===framework)).map(t=>`<tr><td>${esc(t.name)}<span class="subdata">${esc(t.id)}${t.capability!=='prompt'?' | Requiere '+esc(t.capability):''}</span></td><td>${esc(t.mappings.filter(m=>m.framework===framework).map(m=>m.external_id||m.categories.join(', ')).join(', '))}</td><td>${number(t.metrics.valid_adversarial)}</td><td>${number(t.metrics.unique_successful_prompts)}</td><td>${badge(t.label,t.state)}</td></tr>`).join('')||'<tr><td colspan="5">Sin técnicas mapeadas a este marco en el alcance.</td></tr>';renderFrameworkCharts();
}frameworks();
const seenOutcomes=[...new Set(rows.map(outcome))];seenOutcomes.forEach(o=>{const el=document.createElement('option');el.value=o;el.textContent=OUT[o]||o;$('#outcomeFilter').append(el)});[...new Set(rows.map(r=>r.generation))].sort((a,b)=>a-b).forEach(g=>{const el=document.createElement('option');el.value=g;el.textContent='Ronda G'+g;$('#generationFilter').append(el)});
function detail(r){set('detailId',r.id);set('detailPrompt',r.prompt);set('detailAnswer',r.answer||'(La API no devolvi\u00f3 texto.)');$('#detailFacts').innerHTML=badge(OUT[outcome(r)]||outcome(r),OUTCLASS(outcome(r)))+badge(r.expected==='benign'?'Consulta permitida':'Prueba adversarial','neutral')+badge(source(r),(r.tags||[]).includes('llm-generated')?'gen':'neutral')+`<span>HTTP ${r.http_status??'n/a'} | ${number(Math.round(r.latency_ms||0))} ms</span>`;const m=r.metadata||{};const desc={text_blocked:'La respuesta empieza con un aviso de bloqueo. Es una inferencia de texto: no permite ubicar el bloqueo en entrada o salida.',guardrail_blocked:'La API devolvi\u00f3 una se\u00f1al de bloqueo verdadera, sin una etapa reconocida. No se adivina la etapa.',signal_conflict:'El texto de la respuesta y las se\u00f1ales estructuradas se contradicen. Requiere revisar el contrato; no cuenta como \u00e9xito.',accepted_unverified:'Se recibi\u00f3 una respuesta sin evidencia suficiente para confirmar el resultado prohibido.',attack_success:'Resultado confirmado por un criterio de laboratorio expl\u00edcito, un evaluador externo o una revisi\u00f3n humana. Verifica que ese criterio sea adecuado para la pol\u00edtica del cliente.'};set('detailReason',(desc[outcome(r)]||OUT[outcome(r)]||'Clasificaci\u00f3n registrada.')+(r.reason?' Motivo informado: '+r.reason:'')+' Fuente de la se\u00f1al: '+(m.instrumentation||'no registrada')+'.');set('detailReview',r.review_verdict?`Revisi\u00f3n: ${r.review_verdict}. Responsable: ${r.review_reviewer||'no registrado'}. ${r.review_note||''}`:'Sin revisi\u00f3n humana registrada. La similitud de texto y la puntuaci\u00f3n de selecci\u00f3n no son evidencia de \u00e9xito.');$('#detail').showModal();}
$('#closeDetail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});
function evidence(){const q=$('#query').value.toLowerCase(),out=$('#outcomeFilter').value,g=$('#generationFilter').value;const filtered=rows.filter(r=>(out==='all'||outcome(r)===out)&&(g==='all'||String(r.generation)===g)&&(!q||[r.id,r.prompt,r.technique_name,r.operator,r.category].some(s=>String(s||'').toLowerCase().includes(q))));const pages=Math.max(1,Math.ceil(filtered.length/50));page=Math.min(page,pages-1);set('rowCount',`${number(filtered.length)} de ${number(rows.length)} casos`);set('pageLabel',`${page+1} / ${pages}`);$('#previousPage').disabled=page===0;$('#nextPage').disabled=page===pages-1;$('#evidenceRows').innerHTML=filtered.slice(page*50,page*50+50).map(r=>`<tr tabindex="0" data-case="${esc(r.id)}"><td class="mono">G${r.generation}</td><td>${badge(OUT[outcome(r)]||outcome(r),OUTCLASS(outcome(r)))}</td><td>${esc(r.technique_name||r.technique_id)}<span class="subdata">${r.expected==='benign'?'Consulta permitida':'Adversarial'}</span></td><td>${badge(source(r),(r.tags||[]).includes('llm-generated')?'gen':'neutral')}<span class="subdata">${esc(r.operator)}</span></td><td class="prompt-excerpt">${esc(r.prompt.slice(0,110))}${r.prompt.length>110?'...':''}</td><td class="mono">${r.http_status??'n/a'}</td><td class="mono">${number(Math.round(r.latency_ms||0))} ms</td></tr>`).join('')||'<tr><td colspan="7">No hay casos con estos filtros.</td></tr>';$$('[data-case]').forEach(tr=>{tr.onclick=()=>detail(rows.find(r=>r.id===tr.dataset.case));tr.onkeydown=e=>{if(e.key==='Enter')tr.click()}});}
$('#query').oninput=()=>{page=0;evidence()};$('#outcomeFilter').onchange=$('#generationFilter').onchange=()=>{page=0;evidence()};$('#previousPage').onclick=()=>{page--;evidence()};$('#nextPage').onclick=()=>{page++;evidence()};evidence();
$('#fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){set('fullscreenBtn','Usa F11');}};
const gen=A.generator;set('generatorInfo',gen.mode==='rules'?'Estos textos proceden de plantillas y transformaciones programadas. Los resultados ajustan la selecci\u00f3n, pero no se llam\u00f3 a un LLM generador.':`${gen.calls||0} llamadas al modelo ${gen.model||gen.mode}, incluida la comprobaci\u00f3n inicial. El modelo recibi\u00f3 los objetivos y resultados resumidos. Es inferencia con feedback, no entrenamiento de pesos.`);
const graphRows=rows.slice(0,160),generations=[...new Set(graphRows.map(r=>r.generation))].sort((a,b)=>a-b);let points=new Map(),originEdges=[],originStoryAnimations=[],originStoryTimers=[],originStoryToken=0;
function cancelOriginStory({restore=false}={}){originStoryToken++;originStoryAnimations.forEach(a=>{try{a.cancel()}catch(e){}});originStoryTimers.forEach(clearTimeout);originStoryAnimations=[];originStoryTimers=[];if(restore&&route==='evolution')renderOriginGraph(false);}
function later(fn,delay){const id=setTimeout(fn,Math.max(0,delay));originStoryTimers.push(id);return id}
function renderOriginGraph(){points=new Map();originEdges=[];let graph='';const genIndex=new Map(generations.map((g,i)=>[g,i]));generations.forEach((g,i)=>{const group=graphRows.filter(r=>r.generation===g),x=generations.length===1?550:72+i*956/(generations.length-1);graph+=`<g class="generation-group" data-generation="${g}"><line class="generation-guide" x1="${x}" x2="${x}" y1="44" y2="316"/><circle class="generation-halo" cx="${x}" cy="180" r="${18+Math.min(32,group.length*.65)}"/><text class="gen-label" x="${x}" y="24" text-anchor="middle">G${g}</text><text class="gen-count" x="${x}" y="40" text-anchor="middle">${group.length} casos</text></g>`;group.forEach((r,n)=>points.set(r.id,{x,y:58+(n+.5)*244/group.length,g,n}))});let edgeNo=0;graphRows.forEach(r=>{const p=points.get(r.id),parent=points.get(r.parent_id);if(parent){const idx=edgeNo++,targetGeneration=r.generation,d=`M${parent.x} ${parent.y} C${(p.x+parent.x)/2} ${parent.y},${(p.x+parent.x)/2} ${p.y},${p.x} ${p.y}`;originEdges.push({a:parent,b:p,index:idx,targetGeneration,pathId:`edge-${idx}`});graph+=`<path class="lineage-edge-reveal" id="edge-${idx}" data-generation="${targetGeneration}" d="${d}"/><path class="lineage-edge-flow" data-generation="${targetGeneration}" data-edge="edge-${idx}" d="${d}"/>`}});const latest=Math.max(...generations,0);graphRows.forEach(r=>{const p=points.get(r.id);graph+=`<circle class="lineage-node ${r.generation===latest?'latest':''}" data-generation="${r.generation}" data-seq="${p.n}" cx="${p.x}" cy="${p.y}" r="5.5" fill="${OUTCOLOR(outcome(r))}" data-node="${esc(r.id)}"><title>${esc(r.id)} | ${esc(OUT[outcome(r)]||outcome(r))}</title></circle>`});$('#originGraph').innerHTML=graph;$$('[data-node]').forEach(n=>n.onclick=()=>detail(rows.find(r=>r.id===n.dataset.node)));set('graphNote',`Se muestran ${graphRows.length} de ${rows.length} casos. Verde: objetivo adversarial impedido; coral: hallazgo o error; ámbar: rechazo o señal por revisar; lavanda: respuesta sin confirmar. Pulsa Reproducir para ver la historia G0 → G${Math.max(...generations,0)}: nacen los casos, se trazan las relaciones y después recorren partículas por cada vínculo padre/hijo.`);}
function prepareOriginStory(){const stage=$('#originStage');stage.classList.add('origin-story-playing');$$('#originGraph .generation-group').forEach(el=>{el.style.opacity='0'});$$('#originGraph .lineage-node').forEach(el=>{el.style.opacity='0';el.style.transformBox='fill-box';el.style.transformOrigin='center';el.style.transform='scale(.08)'});$$('#originGraph .lineage-edge-reveal').forEach(path=>{let len=1;try{len=path.getTotalLength()}catch(e){}path.dataset.length=String(len);path.style.opacity='0';path.style.strokeDasharray=String(len);path.style.strokeDashoffset=String(len)});$$('#originGraph .lineage-edge-flow').forEach(path=>{path.style.opacity='0'});}
function playOriginStory(onDone){cancelOriginStory();renderOriginGraph();restartOriginAnimation();if(prefersReducedMotion()){onDone?.();return 0}const token=originStoryToken;prepareOriginStory();const stage=$('#originStage');let cursor=110;const groups=new Map(generations.map(g=>[g,$(`#originGraph .generation-group[data-generation="${g}"]`)]));for(let gi=0;gi<generations.length;gi++){const g=generations[gi],group=groups.get(g),nodes=$$(`#originGraph .lineage-node[data-generation="${g}"]`).sort((a,b)=>Number(a.dataset.seq)-Number(b.dataset.seq));if(group){const a=animateEl(group,[{opacity:0,transform:'translateY(-5px)'},{opacity:1,transform:'translateY(0)'}],{duration:520,delay:cursor,easing:'cubic-bezier(.16,.84,.24,1)'});if(a)originStoryAnimations.push(a)}if(gi===0){nodes.forEach((node,i)=>{const delay=cursor+180+i*52,a=animateEl(node,[{opacity:0,transform:'scale(.08)'},{opacity:1,transform:'scale(1)'}],{duration:420,delay,easing:'cubic-bezier(.16,.85,.25,1.28)'});if(a)originStoryAnimations.push(a)});cursor+=Math.max(980,280+nodes.length*52);continue}const edges=$$(`#originGraph .lineage-edge-reveal[data-generation="${g}"]`),flows=$$(`#originGraph .lineage-edge-flow[data-generation="${g}"]`);edges.forEach((path,i)=>{const len=Number(path.dataset.length)||1,delay=cursor+120+i*34,a=animateEl(path,[{opacity:.08,strokeDashoffset:String(len)},{opacity:.82,strokeDashoffset:'0'}],{duration:820,delay,easing:'cubic-bezier(.16,.8,.22,1)'});if(a)originStoryAnimations.push(a)});nodes.forEach((node,i)=>{const delay=cursor+610+i*42,a=animateEl(node,[{opacity:0,transform:'scale(.08)'},{opacity:1,transform:'scale(1)'}],{duration:420,delay,easing:'cubic-bezier(.16,.85,.25,1.28)'});if(a)originStoryAnimations.push(a)});flows.forEach((path,i)=>{const delay=cursor+800+i*30,a=animateEl(path,[{opacity:0},{opacity:.38}],{duration:260,delay,easing:'ease-out'});if(a)originStoryAnimations.push(a)});cursor+=Math.max(1280,900+Math.max(edges.length*34,nodes.length*42))}originIntroDuration=cursor+250;later(()=>{if(token!==originStoryToken)return;stage.classList.remove('origin-story-playing');$$('#originGraph .generation-group,#originGraph .lineage-node').forEach(el=>{el.style.opacity='1';el.style.transform=''});$$('#originGraph .lineage-edge-reveal').forEach(path=>{path.style.opacity='.78';path.style.strokeDasharray='';path.style.strokeDashoffset='0'});$$('#originGraph .lineage-edge-flow').forEach(path=>{path.style.opacity='.36'});onDone?.()},originIntroDuration);return originIntroDuration;}
let originRAF=0,originEpoch=performance.now();
function cubic(a,b,t){const mx=(a.x+b.x)/2,u=1-t;return{x:u*u*u*a.x+3*u*u*t*mx+3*u*t*t*mx+t*t*t*b.x,y:u*u*u*a.y+3*u*u*t*a.y+3*u*t*t*b.y+t*t*t*b.y}}
function resizeOriginCanvas(){const c=$('#originParticles'),stage=$('#originStage');if(!c||!stage)return;const r=stage.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));c.style.width=r.width+'px';c.style.height=r.height+'px';c._d=d;}
function drawOriginParticles(ts){const c=$('#originParticles'),stage=$('#originStage');if(!c||!stage)return;const ctx=c.getContext('2d'),d=c._d||1,w=c.width/d,h=c.height/d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(route!=='evolution'||prefersReducedMotion()){originRAF=requestAnimationFrame(drawOriginParticles);return}const sx=w/1100,sy=h/330,palette=['#a35ee8','#e056c9','#c99bf2','#8f63d8'];originEdges.forEach((e,i)=>{const edge=document.getElementById(e.pathId);if(stage.classList.contains('origin-story-playing')&&edge&&parseFloat(getComputedStyle(edge).opacity)<.3)return;const t=((ts-originEpoch)*.00022+i*.091)%1,p=cubic(e.a,e.b,t),t2=(t-.018+1)%1,q=cubic(e.a,e.b,t2),col=palette[i%palette.length];ctx.beginPath();ctx.moveTo(q.x*sx,q.y*sy);ctx.lineTo(p.x*sx,p.y*sy);ctx.globalAlpha=.16+.22*Math.sin(Math.PI*t);ctx.strokeStyle=col;ctx.lineWidth=.8+(i%3)*.18;ctx.stroke();ctx.beginPath();ctx.globalAlpha=.32+.4*Math.sin(Math.PI*t);ctx.fillStyle=col;ctx.shadowBlur=4;ctx.shadowColor=col;ctx.arc(p.x*sx,p.y*sy,1.05+(i%4)*.23,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});generations.forEach((g,i)=>{const group=$(`#originGraph .generation-group[data-generation="${g}"]`);if(stage.classList.contains('origin-story-playing')&&group&&parseFloat(getComputedStyle(group).opacity)<.25)return;const x=(generations.length===1?550:72+i*956/(generations.length-1))*sx,y=180*sy,isLatest=i===generations.length-1,phase=(ts-originEpoch)*.0016-i*.75,pulse=24+((phase%1+1)%1)*(isLatest?54:35);ctx.beginPath();ctx.globalAlpha=(isLatest?.18:.07)*(1-((phase%1+1)%1));ctx.strokeStyle=isLatest?'#e056c9':'#a35ee8';ctx.lineWidth=isLatest?1.4:1;ctx.arc(x,y,pulse,0,Math.PI*2);ctx.stroke()});ctx.globalAlpha=1;originRAF=requestAnimationFrame(drawOriginParticles)}
function restartOriginAnimation(){originEpoch=performance.now();resizeOriginCanvas();if(!originRAF)originRAF=requestAnimationFrame(drawOriginParticles);}
window.addEventListener('resize',resizeOriginCanvas);
$('#limitations').innerHTML=A.limitations.map(x=>`<p>${esc(x)}</p>`).join('');
function step(){if(!rows.length){set('replayStep','Sin casos');$('#playBtn').disabled=true;return}replay=Math.max(0,Math.min(replay,rows.length-1));const r=rows[replay];set('replayStep',`Caso ${replay+1} / ${rows.length} | G${r.generation} | ${r.id}`);set('replayPrompt',r.prompt);set('replayAnswer',r.answer||r.reason||'Sin texto de respuesta');set('replayOutcome',OUT[outcome(r)]||outcome(r));$('#replayOutcome').className='badge '+OUTCLASS(outcome(r));$$('[data-node]').forEach(n=>n.classList.toggle('selected',n.dataset.node===r.id));$('#previousCase').disabled=replay===0;$('#nextCase').disabled=replay===rows.length-1;}
function stopReplay(){const wasStarting=!!replayStarter;if(timer)clearInterval(timer);if(replayStarter)clearTimeout(replayStarter);timer=null;replayStarter=null;cancelOriginStory({restore:wasStarting&&route==='evolution'});set('playBtn','Reproducir');if(wasStarting&&route==='evolution'){restartOriginAnimation();step();}}
$('#playBtn').onclick=()=>{if(timer||replayStarter){stopReplay();return}if(replay>=rows.length-1)replay=0;set('playBtn','Pausar');set('replayStep','Construyendo G0 → G'+Math.max(...generations,0)+'…');set('replayOutcome','');$('#replayOutcome').className='badge';const startCases=()=>{replayStarter=null;step();timer=setInterval(()=>{replay++;step();if(replay>=rows.length-1)stopReplay()},1800)};const delay=playOriginStory(startCases);if(!delay)startCases();else replayStarter=originStoryTimers[originStoryTimers.length-1]||true};$('#previousCase').onclick=()=>{stopReplay();replay--;step()};$('#nextCase').onclick=()=>{stopReplay();replay++;step()};step();
document.addEventListener('keydown',e=>{if(route==='evolution'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&!$('#detail').open){if(e.code==='Space'){e.preventDefault();$('#playBtn').click()}else if(e.key==='ArrowRight')$('#nextCase').click();else if(e.key==='ArrowLeft')$('#previousCase').click();}});
show(({candidates:'evidence',lineage:'evolution',stage:'evolution'})[location.hash.slice(1)]||location.hash.slice(1)||'overview');
})();
